// In JavaScript there are 5 different data types that can contain values:

// string
// number
// boolean
// object
// function
// There are 6 types of objects:

// Object
// Date
// Array
// String
// Number
// Boolean

// And 2 data types that cannot contain values:

// null
// undefined

// NaN'nin veri türü sayıdır
// Bir dizinin veri türü nesnedir
// Bir tarihin veri türü nesnedir
// null veri türü nesnedir
// Tanımlanmamış bir değişkenin veri türü tanımsızdır *
// Değer atanmamış bir değişkenin veri türü de tanımsızdır *

var x,y,z, a, b, person;
x=7;    //number
y="Javasript"  //String
z=true // boolean
b=undefined   //undefined
a=""    //null string
person = {firstname: "fehmi", lastName:"uyar" }; //object
person= undefined ;
typeof x;
typeof function Test () {} + "<br>";   // function



// //Primite Data
// string    number  boolean   undefined

// //Complex data
// fonksiyon  nesne   

